/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: "autogenerated", dirName: "."}],
  instanaTurbo101: {
    "Instana Turbo 101": [{type: "autogenerated", dirName: "inst-turbo-101"}],
  },
  instanaTurbo201: {
    "Instana Turbo 201": [{type: "autogenerated", dirName: "inst-turbo-201"}],
  },
  waiops101: {
    "Watson AIOps 101": [{type: "autogenerated", dirName: "aiops-101"}],
  },
  // instTurbo101: [{type: "autogenerated", dirName: "inst-turbo-101"}],
  // instTurbo201: [{type: "autogenerated", dirName: "inst-turbo-201"}],
  // waiops101: [{type: "autogenerated", dirName: "aiops-101"}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
}
